"""
Music Recommender Simulation — Terminal Runner
===============================================

Runs five user profiles against the 20-song catalog and prints a clean,
readable layout showing song title, final score, a visual score bar, and
every individual reason generated by score_song().

Profiles:
  0. Default (pop / happy)  — starter profile from the project brief
  1. Late Night Coder       — lofi / focused / acoustic
  2. Weekend Warrior        — pop  / intense / produced
  3. Sunday Morning         — folk / peaceful / acoustic
  4. Dark Commute           — synthwave / moody / produced
"""

from recommender import (
    load_songs, recommend_songs, score_song,
    UserProfile, _score_song_for_user, Song, MAX_SCORE,
)

# ─────────────────────────────────────────────────────────────────────────────
# Layout constants
# ─────────────────────────────────────────────────────────────────────────────
WIDTH      = 66          # total line width
BAR_WIDTH  = 20          # character width of the ASCII score bar
INDENT     = "    "      # 4-space indent for reason lines

# ─────────────────────────────────────────────────────────────────────────────
# Taste Profiles
# ─────────────────────────────────────────────────────────────────────────────

# Profile 0 — Default "pop / happy"
# The starter profile from the project brief.  Used as the primary
# verification case: top results should be bright, energetic pop songs.
default_pop_happy = UserProfile(
    favorite_genre   = "pop",
    favorite_mood    = "happy",
    target_energy    = 0.80,
    likes_acoustic   = False,
    target_valence   = 0.82,
    target_tempo_bpm = 118.0,
)

# Profile 1 — Late Night Coder
late_night_coder = UserProfile(
    favorite_genre   = "lofi",
    favorite_mood    = "focused",
    target_energy    = 0.40,
    likes_acoustic   = True,
    target_valence   = 0.58,
    target_tempo_bpm = 80.0,
)

# Profile 2 — Weekend Warrior
weekend_warrior = UserProfile(
    favorite_genre   = "pop",
    favorite_mood    = "intense",
    target_energy    = 0.92,
    likes_acoustic   = False,
    target_valence   = 0.78,
    target_tempo_bpm = 132.0,
)

# Profile 3 — Sunday Morning
sunday_morning = UserProfile(
    favorite_genre   = "folk",
    favorite_mood    = "peaceful",
    target_energy    = 0.28,
    likes_acoustic   = True,
    target_valence   = 0.68,
    target_tempo_bpm = 74.0,
)

# Profile 4 — Dark Commute
dark_commute = UserProfile(
    favorite_genre   = "synthwave",
    favorite_mood    = "moody",
    target_energy    = 0.75,
    likes_acoustic   = False,
    target_valence   = 0.45,
    target_tempo_bpm = 108.0,
)

ALL_PROFILES = {
    "Default: Pop / Happy ": default_pop_happy,
    "Late Night Coder     ": late_night_coder,
    "Weekend Warrior      ": weekend_warrior,
    "Sunday Morning       ": sunday_morning,
    "Dark Commute         ": dark_commute,
}

# ─────────────────────────────────────────────────────────────────────────────
# Output helpers
# ─────────────────────────────────────────────────────────────────────────────

def _score_bar(score: float, max_score: float = MAX_SCORE, width: int = BAR_WIDTH) -> str:
    """
    Renders an ASCII progress bar for a score value.

    Example:  score=6.83, max=7.00, width=20
      filled = round(6.83 / 7.00 * 20) = 20  ->  [####################]  99%

    Uses only ASCII '#' and '.' so it works on any Windows/Mac/Linux terminal
    regardless of code-page or font support.
    """
    filled = round((score / max_score) * width)
    filled = max(0, min(width, filled))        # clamp to [0, width]
    bar    = "#" * filled + "." * (width - filled)
    pct    = score / max_score * 100
    return f"[{bar}] {score:.2f}/{max_score:.2f} ({pct:.1f}%)"


def _reason_prefix(reason: str) -> str:
    """
    Returns a '+', '~', or '-' prefix based on how well the feature scored.

    '+' = strong match  (>= 80% of the feature's max points)
    '~' = partial match (>= 40% of max)
    '-' = weak match    (<  40% of max)
    """
    try:
        # reasons are formatted as "label (+earned / max)"
        earned = float(reason.split("(+")[1].split(" /")[0])
        maxi   = float(reason.split("/ ")[1].rstrip(")"))
        ratio  = earned / maxi if maxi > 0 else 0
        if ratio >= 0.80:
            return "+"
        if ratio >= 0.40:
            return "~"
        return "-"
    except (IndexError, ValueError, ZeroDivisionError):
        # categorical matches like "genre match: 'pop' (+2.00)" have no "/ max"
        return "+"


def print_profile_header(label: str, profile: UserProfile) -> None:
    """Prints the decorated profile header block."""
    print("=" * WIDTH)
    print(f"  PROFILE : {label.strip()}")
    print(f"  Genre   : {profile.favorite_genre:<12}  Mood    : {profile.favorite_mood}")
    print(f"  Energy  : {profile.target_energy:<12}  Valence : {profile.target_valence}")
    print(f"  Tempo   : {profile.target_tempo_bpm} BPM       Acoustic: {profile.likes_acoustic}")
    print("=" * WIDTH)


def print_recommendation(rank: int, song: dict, score: float, reasons: list) -> None:
    """
    Prints one recommendation in the clean card layout:

      #1  Sunrise City
          by Neon Echo
          Genre: pop  |  Mood: happy
          -------------------------------------------------------
          Score:  [####################] 6.96/7.00 (99.4%)
          Why this song?
            +  genre match: 'pop' (+2.00)
            +  mood match: 'happy' (+1.50)
            +  energy: 0.82 ~ target 0.80 (+1.49 / 1.50)
            +  valence: 0.84 ~ target 0.82 (+1.00 / 1.00)
            +  produced texture: 0.18 (+0.61 / 0.75)
            +  tempo: 118 BPM ~ target 118 BPM (+0.25 / 0.25)
    """
    divider = "  " + "-" * (WIDTH - 4)
    title   = song["title"]
    artist  = song["artist"]
    genre   = song["genre"]
    mood    = song["mood"]

    print(f"  #{rank}  {title}")
    print(f"      by {artist}")
    print(f"      Genre: {genre:<14}  Mood: {mood}")
    print(divider)
    print(f"      Score:  {_score_bar(score)}")
    print(f"      Why this song?")
    for reason in reasons:
        prefix = _reason_prefix(reason)
        print(f"        {prefix}  {reason}")
    print()


# ─────────────────────────────────────────────────────────────────────────────
# Differentiation snapshot
# ─────────────────────────────────────────────────────────────────────────────

def run_differentiation_test(songs_dict: list) -> None:
    """
    Quick sanity check: shows how each profile separates the two most
    contrasting songs in the catalog.
    """
    storm = next((s for s in songs_dict if s["title"] == "Storm Runner"), None)
    rain  = next((s for s in songs_dict if s["title"] == "Library Rain"), None)
    if not storm or not rain:
        return

    def to_song(d: dict) -> Song:
        return Song(
            id=d["id"], title=d["title"], artist=d["artist"],
            genre=d["genre"], mood=d["mood"], energy=d["energy"],
            tempo_bpm=d["tempo_bpm"], valence=d["valence"],
            danceability=d["danceability"], acousticness=d["acousticness"],
        )

    storm_song = to_song(storm)
    rain_song  = to_song(rain)

    print("=" * WIDTH)
    print("  DIFFERENTIATION SNAPSHOT")
    print("  Storm Runner (rock/intense) vs Library Rain (lofi/chill)")
    print("=" * WIDTH)
    print(f"  {'Profile':<24} {'Storm Runner':>13} {'Library Rain':>13} {'Gap':>7}")
    print(f"  {'-'*24} {'-'*13} {'-'*13} {'-'*7}")
    for label, profile in ALL_PROFILES.items():
        s = _score_song_for_user(storm_song, profile)
        r = _score_song_for_user(rain_song,  profile)
        g = abs(s - r)
        w = "<- rock" if s > r else "<- lofi"
        print(f"  {label.strip():<24} {s:>7.2f} ({s/MAX_SCORE*100:>4.1f}%)"
              f"  {r:>7.2f} ({r/MAX_SCORE*100:>4.1f}%)  {g:>5.2f} {w}")
    print()


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    songs = load_songs("data/songs.csv")
    print(f"Loaded songs: {len(songs)}")
    print()

    for label, profile in ALL_PROFILES.items():
        print_profile_header(label, profile)

        recs = recommend_songs(
            user_prefs={
                "genre":            profile.favorite_genre,
                "mood":             profile.favorite_mood,
                "energy":           profile.target_energy,
                "likes_acoustic":   profile.likes_acoustic,
                "target_valence":   profile.target_valence,
                "target_tempo_bpm": profile.target_tempo_bpm,
            },
            songs=songs,
            k=5,
        )

        print()
        print(f"  Top 5 Recommendations")
        print()
        for rank, (song, score, reasons) in enumerate(recs, 1):
            print_recommendation(rank, song, score, reasons)

    run_differentiation_test(songs)


if __name__ == "__main__":
    main()
